### ISSUE TITLE
Cannot download datasets

### ISSUE THREAD

**Issue by xinsu626** [LIAAD/tieval#15]
Hello, I was trying to download the TimeBank dataset using the example code from the readme, but it threw the following errors. Could you please help me with this?

 ```
'https://drive.inesctec.pt/s/KmeTs6LqnmzRr2s/download'
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "Temporal-Relation-Extraction/explore.py", line 5, in <module>
    datasets.download("TimeBank", data_path)
  File "site-packages/tieval/datasets/__init__.py", line 48, in download
    download_url(metadata.url, path)
  File "site-packages/tieval/utils.py", line 30, in download_url
    raise Exception(f"Request code: {response.status_code}")
Exception: Request code: 404
```

**Comment by asdc-s5** [comment]
I have the same problem, can anyone help on this?

**Comment by hmosousa** [comment]
Hi @xinsu626 and @asdc-s5 

Really sorry for the late (really late) response. 

Thank you for reporting the bug.

For some reason the links to download some of the datasets has been broken. In the meantime, I have update the download ulrs. I will know patch the package on PyPI.

All the best,
Hugo
